swagger: '2.0'
info:
  title: KYC API
  description: Exposes publisher calls 
  version: '1'
schemes:
  - http
  - https
produces:
  - application/json
paths:
  "/register_constrain":
    get:
      description: Register topic for pub
      operationId: api.explorer.register_constrain
      parameters:
        - in: query
          name: schema
          default: "email"
          type: string
          required: true
          description: schemas saparate with ,
      responses:
        '200':
          description: schema
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/build_tx":
    get:
      description: Register topic for pub
      operationId: api.explorer.build_tx
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account name to create
        - in: query
          name: WIF
          default: "5KWTrrQMyD7Ez62viB36r75ur9ZJ6DPu3qkSa2eDcpE99XfD8ye"
          type: string
          required: true
          description: priv key
      responses:
        '200':
          description: view_constrains
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json


  "/view_constrains":
    get:
      description: Register topic for pub
      operationId: api.explorer.view_constrains
      parameters:
        - in: query
          name: token
          default: "123456"
          type: string
          required: true
          description: token
      responses:
        '200':
          description: view_constrains
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/unregister_contrain":
    get:
      description: Register topic for pub
      operationId: api.explorer.unregister_contrain
      parameters:
        - in: query
          name: k
          default: "1563334118"
          type: string
          required: true
          description: key as timestamp
      responses:
        '200':
          description: api.explorer.unregister_contrain
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/genCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.genCode
      parameters:
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: genCode
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json
  "/sendVerifyCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.sendVerifyCode
      parameters:
        - in: query
          name: code
          default: "090990"
          type: string
          required: true
          description: code
        - in: query
          name: dest
          default: "qi.sun@cybex.io"
          type: string
          required: true
          description: dest
        - in: query
          name: ttype
          default: 1
          type: integer
          required: true
          description: 0->email, 1->phone
      responses:
        '200':
          description: sendVerifyCode
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/jso

  "/verifyCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.verifyCode
      parameters:
        - in: query
          name: code
          default: "909090"
          type: string
          required: true
          description: code
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account name
      responses:
        '200':
          description: verifyCode
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json
  "/getKYC":
    get:
      description: Register topic for pub
      operationId: api.explorer.getKYC
      parameters:
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account 
      responses:
        '200':
          description: getKYC
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json
  "/kycCreate":
    post:
      description: Register topic for pub
      operationId: api.explorer.kycCreate
      parameters:
        - in: body
          name: data
          required: true
          description: JSON you want to get
          schema:
            $ref: '#/definitions/KYCCREATE'
      responses:
        '200':
          description: kycCreate
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/kycRmv":
    get:
      description: Register topic for pub
      operationId: api.explorer.kycRmv
      parameters:
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account to rmv
        - in: query
          name: signature
          default: "*"
          type: string
          required: true
          description: signature
      responses:
        '200':
          description: remove from kyc
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json


  "/kycUpd":
    post:
      description: Register topic for pub
      operationId: api.explorer.kycUpd
      parameters:
        - in: body
          name: data
          required: true
          description: JSON you want to get
          schema:
            $ref: '#/definitions/KYCUPDATE'
      responses:
        '200':
          description: update kyc
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/get_account":
    get:
      description: Register topic for pub
      operationId: api.explorer.get_account
      parameters:
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account to rmv
      responses:
        '200':
          description: remove from kyc
        '500':
          description: Error processing parameters
      tags:
        - api
      produces:
        - application/json


  "/register_acct":
    post:
      description: Register topic for pub
      operationId: api.explorer.register_acct
      parameters:
        - in: body
          name: obj
          required: true
          schema:
            $ref: '#/definitions/Content'
      responses:
        '200':
          description: Registered
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api



definitions:
  Content:
    required:
      - name
      - signature
      - email
      - kyc_id
      - owner_key
      - active_key
      - memo_key
      - new
    properties:
      signature:
        type: string
        description: a
      name:
        type: string
        description: a
      email:
        type: string
        description: a
      kyc_id:
        type: string
        description: a
      wechat:
        type: string
        description: a
      phone:
        type: string
        description: a
      owner_key:
        type: string
        description: a
      active_key:
        type: string
        description: a
      memo_key:
        type: string
        description: a
      new:
        type: boolean
        description: a
  KYCUPDATE:
    required:
      - signature
      - name
      - kyc_id
    properties:
      signature:
        type: string
        description: signature
      kyc_id:
        type: string
        description: a
      email:
        type: string
        description: email
      wechat:
        type: string
        description: phone
      phone:
        type: string
        description: phone
      name:
        type: string
        description: The account name
      accid:
        type: string
        description: The account id

  KYCCREATE:
    required:
      - signature
      - name
      - kyc_id
    properties:
      signature:
        type: string
        description: signature
      kyc_id:
        type: string
        description: a
      email:
        type: string
        description: email
      wechat:
        type: string
        description: wechat
      phone:
        type: string
        description: phone
      name:
        type: string
        description: The account name
      accid:
        type: string
        description: The account id
  SuccessResponse:
    required:
      - service
    properties:
      service:
        type: string
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
