swagger: '2.0'
info:
  title: KYC API
  description: Exposes publisher calls 
  version: '1'
schemes:
  - http
  - https
produces:
  - application/json
paths:
  "/register_constrain":
    get:
      description: api.explorer.register_constrain
      operationId: api.explorer.register_constrain
      parameters:
        - in: query
          name: schema
          default: "email"
          type: string
          required: true
          description: you can't select a required field(like signature ), only optional fields can be set into; fileds are separated by ,
        - in: query
          name: kyc_id
          default: "1234"
          type: string
          required: true
          description: timestamp as key
      responses:
        '200':
          description: schema
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json
  "/debug_verify_tx":
    get:
      description: Register topic for pub
      operationId: api.explorer.debug_verify_tx
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account name to create
        - in: query
          name: sig
          default: "111"
          type: string
          required: true
          description: sig
      responses:
        '200':
          description: debug sig
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - debug
      produces:
        - application/json


  "/build_tx":
    get:
      description: Register topic for pub
      operationId: api.explorer.build_tx
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account name to create
        - in: query
          name: WIF
          default: "5KWTrrQMyD7Ez62viB36r75ur9ZJ6DPu3qkSa2eDcpE99XfD8ye"
          type: string
          required: true
          description: priv key
      responses:
        '200':
          description: debug sig
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - debug
      produces:
        - application/json


  "/view_constrains":
    get:
      description: Register topic for pub
      operationId: api.explorer.view_constrains
      parameters:
        - in: query
          name: token
          default: "123456"
          type: string
          required: true
          description: token
      responses:
        '200':
          description: view_constrains
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json

  "/unregister_contrain":
    get:
      description: Register topic for pub
      operationId: api.explorer.unregister_contrain
      parameters:
        - in: query
          name: k
          default: "1563334118"
          type: string
          required: true
          description: key as timestamp
      responses:
        '200':
          description: api.explorer.unregister_contrain
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
      produces:
        - application/json

  "/genCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.genCode
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: genCode
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - verify
      produces:
        - application/json
  "/sendVerifyCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.sendVerifyCode
      parameters:
        - in: query
          name: code
          default: "090990"
          type: string
          required: true
          description: code
        - in: query
          name: dest
          default: "qi.sun@cybex.io"
          type: string
          required: true
          description: dest
        - in: query
          name: ttype
          default: 1
          type: integer
          required: true
          description: 0->email, 1->phone
      responses:
        '200':
          description: sendVerifyCode
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - verify
      produces:
        - application/jso

  "/verifyCode":
    get:
      description: Register topic for pub
      operationId: api.explorer.verifyCode
      parameters:
        - in: query
          name: code
          default: "909090"
          type: string
          required: true
          description: code
        - in: query
          name: account
          default: "nathan"
          type: string
          required: true
          description: account name
      responses:
        '200':
          description: verifyCode
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - verify
      produces:
        - application/json
  "/getKYC_golden":
    get:
      description: Register topic for pub
      operationId: api.explorer.getKYC_golden
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account 
        - in: query
          name: signature
          default: "203148e0a9749808f99818d779210bd5f305699d7b4fc09cacdd43322e5a783e2946a149c0549078fbcc2e7da0c92c74c6eb179cf7152c5879b29e9c09c2386c31"
          type: string
          required: true
          description: sig
      responses:
        '200':
          description: getKYC
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json

  "/getKYC":
    get:
      description: Register topic for pub
      operationId: api.explorer.getKYC
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account 
        - in: query
          name: signature
          default: "203148e0a9749808f99818d779210bd5f305699d7b4fc09cacdd43322e5a783e2946a149c0549078fbcc2e7da0c92c74c6eb179cf7152c5879b29e9c09c2386c31"
          type: string
          required: true
          description: sig
      responses:
        '200':
          description: getKYC
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json
  "/kycCreate":
    post:
      description: Register topic for pub
      operationId: api.explorer.kycCreate
      parameters:
        - in: body
          name: data
          required: true
          description: JSON you want to get
          schema:
            $ref: '#/definitions/KYCCREATE'
      responses:
        '200':
          description: kycCreate
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json

  "/kycRmv":
    get:
      description: Register topic for pub
      operationId: api.explorer.kycRmv
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account to rmv
        - in: query
          name: signature
          default: "203148e0a9749808f99818d779210bd5f305699d7b4fc09cacdd43322e5a783e2946a149c0549078fbcc2e7da0c92c74c6eb179cf7152c5879b29e9c09c2386c31"
          type: string
          required: true
          description: signature
      responses:
        '200':
          description: remove from kyc
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json


  "/kycUpd":
    post:
      description: Register topic for pub
      operationId: api.explorer.kycUpd
      parameters:
        - in: body
          name: data
          required: true
          description: JSON you want to get
          schema:
            $ref: '#/definitions/KYCUPDATE'
      responses:
        '200':
          description: update kyc
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - kyc
      produces:
        - application/json

  "/get_account":
    get:
      description: Register topic for pub
      operationId: api.explorer.get_account
      parameters:
        - in: query
          name: account
          default: "sunxiaoqi-11"
          type: string
          required: true
          description: account to rmv
      responses:
        '200':
          description: remove from kyc
        '500':
          description: Error processing parameters
      tags:
        - api
        - chain
      produces:
        - application/json


  "/register_acct":
    post:
      description: Register topic for pub
      operationId: api.explorer.register_acct
      parameters:
        - in: body
          name: obj
          required: true
          schema:
            $ref: '#/definitions/Content'
      responses:
        '200':
          description: Registered
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - faucet
        - kyc




  "/get_eto_subscription":
    get:
      description: api.explorer.get_eto_subscription
      operationId: api.explorer.get_eto_subscription
      parameters:
        - in: query
          name: eto_id
          default: "1"
          type: string
          required: true
          description: jdajidaoi
        - in: query
          name: account
          default: "1.2.123"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: get_eto_subscription
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form
      produces:
        - application/json


  "/get_survey":
    get:
      description: api.explorer.get_survey
      operationId: api.explorer.get_survey
      parameters:
        - in: query
          name: eto_id
          default: "1"
          type: string
          required: true
          description: jdajidaoi
        - in: query
          name: account
          default: "1.2.123"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: get survey
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form
      produces:
        - application/json



  "/eto_subscription":
    post:
      description: Register topic for pub
      operationId: api.explorer.eto_subscription 
      parameters:
        - in: body
          name: obj
          required: true
          schema:
            $ref: '#/definitions/Subscription'
      responses:
        '200':
          description: subscription stored
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form



  "/update_eto_subscription":
    post:
      description: Register topic for pub
      operationId: api.explorer.update_eto_subscription
      parameters:
        - in: body
          name: obj
          required: true
          schema:
            $ref: '#/definitions/Subscription'
      responses:
        '200':
          description: subscription stored
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form



  "/rmv_eto_subscription":
    get:
      description: api.explorer.rmv_eto_subscription
      operationId: api.explorer.rmv_eto_subscription
      parameters:
        - in: query
          name: eto_id
          default: "1"
          type: string
          required: true
          description: jdajidaoi
        - in: query
          name: account
          default: "1.2.123"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: rmv_eto_subscription
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form

  "/survey":
    post:
      description: Register topic for pub
      operationId: api.explorer.survey
      parameters:
        - in: body
          name: obj
          required: true
          schema:
            $ref: '#/definitions/Survey'
      responses:
        '200':
          description: Survey stored
          schema:
            $ref: '#/definitions/SuccessResponse'
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form
  "/rmv_survey":
    get:
      description: api.explorer.rmv_survey
      operationId: api.explorer.rmv_survey
      parameters:
        - in: query
          name: eto_id
          default: "1"
          type: string
          required: true
          description: jdajidaoi
        - in: query
          name: account
          default: "1.2.123"
          type: string
          required: true
          description: account
      responses:
        '200':
          description: remove survey
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form
      produces:
        - application/json

  "/get_accounts_by_kyc":
    get:
      description: api.explorer.get_accounts_by_kyc
      operationId: api.explorer.get_accounts_by_kyc
      parameters:
        - in: query
          name: kyc_id
          default: "1"
          type: string
          required: true
          description: eto id
      responses:
        '200':
          description: eto_id
        '500':
          description: Error processing parameters
          schema:
            $ref: '#/definitions/ErrorResponse'
      tags:
        - api
        - eto_form
        - kyc




definitions:
  Subscription:
    required:
      - eto_id
      - account
      - symbol
      - asset_id
    properties:
      eto_id:
        type: string
        description: a
      asset_id:
        type: string
        description: a
      symbol:
        type: string
        description: a
      account:
        type: string
        description: a

  Survey:
    required:
      - eto_id
      - questionnaire
      - account
    properties:
      eto_id:
        type: string
        description: a
      questionnaire:
        type: string
        description: a
      account:
        type: string
        description: a
  Content:
    required:
      - name
      - signature
      - email
      - kyc_id
      - owner_key
      - active_key
      - memo_key
      - new
    properties:
      signature:
        type: string
        description: a
      name:
        type: string
        description: a
      email:
        type: string
        description: a
      kyc_id:
        type: string
        description: a
      wechat:
        type: string
        description: a
      phone:
        type: string
        description: a
      owner_key:
        type: string
        description: a
      active_key:
        type: string
        description: a
      memo_key:
        type: string
        description: a
      new:
        type: boolean
        description: a
  KYCUPDATE:
    required:
      - signature
      - name
    properties:
      signature:
        type: string
        description: signature
      kyc_id:
        type: string
        description: a
      email:
        type: string
        description: email
      wechat:
        type: string
        description: phone
      phone:
        type: string
        description: phone
      name:
        type: string
        description: The account name
      accid:
        type: string
        description: The account id

  KYCCREATE:
    required:
      - signature
      - name
      - kyc_id
    properties:
      signature:
        type: string
        description: signature
      kyc_id:
        type: string
        description: kyc_id
      email:
        type: string
        description: email
      date:
        type: string
        description: date
      submitted:
        type: boolean
        description: submitted 
      recommend:
        type: string
        description: recommend
      token:
        type: string
        description: token
      refer:
        type: string
        description: refer
      coinAge:
        type: string
        description: coinAge
      wechat_name:
        type: string
        description: wechat
      wechat_id:
        type: string
        description: wechat
      phone:
        type: string
        description: phone
      name:
        type: string
        description: The account name
      accid:
        type: string
        description: The account id
  SuccessResponse:
    required:
      - service
    properties:
      service:
        type: string
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: integer
      message:
        type: string
